version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=voluntaweb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=voluntaweb
      - MYSQL_PASSWORD=voluntaweb
    ports:
      - 3306:3306


  voluntaweb:
    image: dserranoc/voluntaweb
    entrypoint: ["java", "-jar", "backend.jar"]
    ports:
      - 8443:8443
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/voluntaweb?useSSL=false
      - SPRING_DATASOURCE_USERNAME=voluntaweb
      - SPRING_DATASOURCE_PASSWORD=voluntaweb
