version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=voluntaweb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=voluntaweb
      - MYSQL_PASSWORD=voluntaweb
    ports:
      - 3306:3306  
    healthcheck:
    interval: 15s
    timeout: 15s
    retries: 10


  voluntaweb:
    image: theroxd4n/voluntaweb:latest
    restart: always
    entrypoint: ["java", "-jar", "backend.jar"]
    ports:
      - 8443:8443
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/voluntaweb?useSSL=false
      - SPRING_DATASOURCE_USERNAME=voluntaweb
      - SPRING_DATASOURCE_PASSWORD=voluntaweb
